Corrected identation for 'modules' property.
I believe that this is the correct identation for the modules property. (See https://github.com/brunch/brunch/blob/master/docs/config.md)
It wasn't working before. Now the sourceUrl is added to the compiled javascript.
However, now the application doesn't work and the following error comes up:

    Uncaught Error: Cannot find module "handlebars" vendor.js:61
    Uncaught TypeError: Cannot call method 'map' of undefined

Using Ember RC5 and Handlebars RC4.

Real source maps are coming in brunch 1.7.0 (https://github.com/brunch/brunch/blob/master/CHANGELOG.md), but meanwhile we should get this working. It really helps debugging a lot.

Any hints?